kind: Pod
apiVersion: v1
metadata:
  name: apigw-app
  labels:
    app: apigw
spec:
  containers:
  - name: apigw-app
    image: luisgf1810/apigw:latest
---
kind: Service
apiVersion: v1
metadata:
  name: apigw-service
spec:
  selector:
    app: apigw
  ports:
  - port: 8081
---
kind: Pod
apiVersion: v1
metadata:
  name: appui-app
  labels:
    app: appui
spec:
  containers:
  - name: appui-app
    image: luisgf1810/appui:latest
---
kind: Service
apiVersion: v1
metadata:
  name: appui-service
spec:
  selector:
    app: appui
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appui-service
            port:
              number: 8080
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: apigw-service
            port:
              number: 8081
---
